### ISSUE TITLE
Symbols들은 그냥 폰트에서 제거해주시면 안될까요?..

### ISSUE THREAD

**Issue by okgosu** [naver/d2codingfont#13]
This issue created by **taeguenv8**  | 2016/08/10 16:00:24

---

소중한 폰트 감사히 쓰고있습니다. 

유니코드 영역중 기호관련해서 사소한 불편사항이 있어 이슈를 남깁니다.

D2 Coding 폰트가 몇개의 symbol들은 존재하는데 대부분의 글리프가 존재하지않아 레이아웃이 조화롭지가 않아서요.

솔직히 모든 기호 글리프들을 만드시는게 더 어려우실테니 그냥 제거만 해주셔도 감지덕지입니다.

대표적으로 Ballot Box U+2610 가 그 예인데 해당 기호는 폰트에 존재하지만 Ballot Box with X U+2612 는 존재하지 않아 굉장히 부조화스럽습니다.....

Windows가 유니코드중 기호들을 보여줄때 사용하는 Segoe UI Symbol 폰트로 그냥 기호들을 표시해주는게 그나마 조화로운거 같습니다.

해당 글리프들의 영역도 남겨 놓겠습니다.

Miscellaneous Symbols 2600—26FF 

Miscellaneous Symbols and Pictographs 1F300—1F5FF

---
### Attachments
- 문제.png
  
  ![문제.png](https://github.com/okgosu/d2codingfont/wiki/attachFile/106641/68543/617b737edf0d4822dad076c4bbec7380.png)
- 안보여.png
  
  ![안보여.png](https://github.com/okgosu/d2codingfont/wiki/attachFile/106641/68544/91871b285174befa584cbbac198cf837.png)

**Comment by okgosu** [comment]
날카로운 의견 정말 감사합니다.

**Comment by the1900** [comment]
오 제가 쓴 의견인데 그대로 이슈등록해주셨네요ㅋㅋㅋㅋ 감사합니다.

**Comment by okgosu** [comment]
https://github.com/naver/d2codingfont/releases/tag/VER1.3 에 필요한 심볼들은 어느 정도 추가되었습니다. 본 이슈는 종료합니다. 감사합니다.
