### ISSUE TITLE
pycharm에서 일부 글자들이 한자로 표시가 됩니다.

### ISSUE THREAD

**Issue by arisu** [naver/d2codingfont#34]
네이버 저장소에 lesuljoker님이 등록한 내용과 동일합니다. 
참조 : [d2 coding 깃헙 최신버전 사용중](http://dev.naver.com/projects/d2coding/issue/106928) 

Pycharm community 2016.2.1 사용 중인데 
일부 글자들이 한자로 표시가 됩니다. 

기존 파일을 열었을 때도 한자로 표시되고 
새로 입력을 해도 한자로 표시가 됩니다.

**Comment by okgosu** [comment]
네, 확인해보겠습니다. 제보 감사합니다.

**Comment by crucifyer** [comment]
버전 1.2 에서 jetbrains 모든 제품에 문제가 있네요. 1.1 로 내려야 합니다.

**Comment by okgosu** [comment]
Pycharm 2016.2.3 에서 테스트 결과 에러가 재현되지 않았습니다. 

@crucifyer 님, 저는 jetbrains의  IntelliJ 사용중인데, 그런 현상 없었습니다.

본 이슈는 종료하고, 이슈 재현이 되면 스샷과 함께 다시 이슈로 올려주시길 바래요.

**Comment by crucifyer** [comment]
![image](https://user-images.githubusercontent.com/1300668/28407338-be4ed030-6d6e-11e7-8c27-83a0430d5217.png)
여전합니다. phpstorm 2017.1.4 버전이고,
D2Coding 1.2 에서
주황색으로 하일라이트 되는 모든 글자가 한자처럼 보이는 글꼴이 겹쳐져 표기됩니다.
1.1 은 이상 없습니다.

**Comment by ibin79** [comment]
1.2 버전에서  D2CodingBold.ttf 설치시에만 문제가 확인됩니다.

- D2CodingBold.ttf 로 설치시 문제 발생

![2017-08-10 09 54 46](https://user-images.githubusercontent.com/6302755/29149955-5a282562-7db2-11e7-9b88-7d2c6edf36b4.PNG)


- D2Coding.ttc 로 설치시 문제 없음

![2017-08-10 09 52 44](https://user-images.githubusercontent.com/6302755/29149952-56d33c76-7db2-11e7-888a-320cb340ef54.PNG)


# 임시 해결 방법

- ttc 파일에는 D2Coding.ttf 와 D2CodingBold.ttf 모두 포함되어 있습니다.

![2017-08-10 09 58 48](https://user-images.githubusercontent.com/6302755/29150038-f9e26ff4-7db2-11e7-8f70-5a9e34646021.PNG)

> 따라서 문제가 있는 분들은 D2Coding.ttc 파일만 설치하면 해결됩니다.

- 테스트 환경 : Windows 7 + PhpStorm 2017.2.1

**Comment by ibin79** [comment]
저도 1.2 버전으로 재설치후 문제가 있었는데요.


![2017-08-10 09 54 46](https://user-images.githubusercontent.com/6302755/29149955-5a282562-7db2-11e7-9b88-7d2c6edf36b4.PNG)


모든 프로그램 닫고 다시 D2Coding.ttc 를 설치하니 해결되네요.

![2017-08-10 09 52 44](https://user-images.githubusercontent.com/6302755/29149952-56d33c76-7db2-11e7-888a-320cb340ef54.PNG)


> 테스트 환경 : Windows 7 + PhpStorm 2017.2.1

**Comment by crucifyer** [comment]
윈도10 2017.2.1 증상이 고쳐지지 않습니다. ttc 로 몇번이나 덮어봤습니다.

**Comment by crucifyer** [comment]
지우고 ttf 두개로 하니 증상이 없습니다.

**Comment by okgosu** [comment]
본 이슈는 ttf로 해서 해결 된 것으로 이해하고 이슈 종료합니다. 감사합니다.
