### ISSUE TITLE
powerline 심볼 추가 요청 드립니다.

### ISSUE THREAD

**Issue by pokev25** [naver/d2codingfont#35]
d2coding 1.0 파워라인 심볼 패치 한걸 사용하고 있는데

정식으로 심볼이 들어가면 좋겠습니다.

http://dalgona.128bit.tech/d2coding-powerline/

**Comment by okgosu** [comment]
아...1.0으로 작업하셨군요. 공유 감사드립니다^^ 
1.2버전에는 포함안된 심볼을 말씀하시는건가요?
https://github.com/naver/d2codingfont/releases/tag/VER1.21

**Comment by pokev25** [comment]
아..제가 한건 아니고 저도 저걸 가져다 쓰고 있었습니다.

1.2에 포함안된 심볼을 말하는게 맞습니다.

**Comment by maxtortime** [comment]
@pokev25 태그명은 마이그레이션 과정에서 릴리즈 순서를 맞추느라 1.21로 하게 되었는데 1.2 버전이 맞습니다. 다만 description에 2.5라고 되있는건 오타 같네요..

**Comment by okgosu** [comment]
릴리즈 노트에 '2.5 버전 다운로드' 라는 링크 -> 1.2로 수정했어요.

**Comment by okgosu** [comment]
https://github.com/naver/d2codingfont/releases/tag/VER1.3 에 반영되어 이슈 종료합니다. 감사합니다.
