### ISSUE TITLE
받침'ㅂ'이 가독성에 문제가 있어 보입니다.

### ISSUE THREAD

**Issue by kyjelblue** [naver/d2codingfont#36]
ㅁ받침과 ㅂ받침의 구분이 폰트 크기와 관계없이 잘 구분이 되지 않는군요.
더구나 코딩과 쉘 환경 등이 주 용도인 고정폭 글꼴이라는 점에서 폰트 크기를 필요 이상으로 조정할 이유도 없고요.
요컨대 ㅂ받침의 가운데 획을 좀 더 내려주시면 어떨까 하네요.

좋은 폰트 감사히 사용 중입니다.

**Comment by okgosu** [comment]
의견 감사합니다. 폰트디자이너와 검토해보겠습니다.

**Comment by Ra-Sep-Re-Tep** [comment]
안녕하세요, 저도 kyjelblue 님의 의견에 공감합니다.
감사합니다, 좋은 폰트 너무 잘 쓰고 있습니다~!

**Comment by okgosu** [comment]
네, 의견 감사합니다.
확인해 보겠습니다.

**Comment by okgosu** [comment]
https://github.com/naver/d2codingfont/releases/tag/VER1.3 에 반영되어 이슈 종료합니다. 감사합니다.
