### ISSUE TITLE
UltraEdit에서 좀 깨져 보입니다.

### ISSUE THREAD

**Issue by lotiony** [naver/d2codingfont#37]
나눔고딕코딩폰트를 사용하다가 D2Coding으로 변경했습니다.
여러 개발 환경에 다 같이 바꿔봤는데  유독 울트라에디트에서만 좀 깨져 보이는것 같습니다.
마치 ClearType이 적용 안된 것처럼 보이는데요 
14폰트를 사용하면 그때부터는 깔끔하게 보입니다. 11, 10 등  기존 나눔고딕코딩 설정과 동일하게 셋팅하면 깨져보여요.. 이게 울트라에디트 문제일지 폰트문제일지 잘 모르겠지만 일단 남겨봅니다..

ultraedit_d2coding_14폰트
![image](https://cloud.githubusercontent.com/assets/16128718/21598708/b3a5e47c-d1a4-11e6-8bae-9d6111e912ab.png)

ultraedit_d2coding_11폰트
![image](https://cloud.githubusercontent.com/assets/16128718/21598715/ca04966e-d1a4-11e6-9d57-4140f27de010.png)

ultraedit_d2coding_10폰트
![image](https://cloud.githubusercontent.com/assets/16128718/21598717/e5a18288-d1a4-11e6-86ca-e7952a92cd22.png)

ultraedit_나눔고딕코딩_10폰트
![image](https://cloud.githubusercontent.com/assets/16128718/21598721/f3bb0e20-d1a4-11e6-9da7-8980f36f288b.png)

SSMS2014_d2coding_10폰트
![image](https://cloud.githubusercontent.com/assets/16128718/21598722/fe9452c0-d1a4-11e6-8545-ba04cb4fc5c9.png)

VS2015_d2coding_10폰트
![image](https://cloud.githubusercontent.com/assets/16128718/21598725/0a216ace-d1a5-11e6-8fe9-4b29973f1962.png)

**Comment by okgosu** [comment]
울트라에디터 설정 이슈로 보입니다.

설정 - 편집기 표시 - 고급 - 글꼴 품질에서 [Non Antialised Quality]를 선택하시길 바래요.
