### ISSUE TITLE
특수문자/기호

### ISSUE THREAD

**Issue by dist777** [naver/d2codingfont#38]
특수문자/기호

영/한/일 혼용에 쓸 폰트를 고민하던 중 D2를 알게 되서
이후로는 거의 모든 환경에 D2 를 사용하고 있답니다.
무한감사드립니다.

Ver. 1.2 를 테스트해보고 있는데요
한가지 건의드리고 싶은 건
    ◇□◆■Δ←↓↑→ ↔↕↗↙↖↘
위와 같은 특수문자/기호의 경우
대부분 2byte문자 = 영문 2칸을 차지하는 문자일텐데
모두 1칸으로 인식되더군요.
기왕이면 원래 차지해야 할 칸 수를 정확히 차지하는 편이 좋지 않겠나 하는 생각입니다.

( 본 현상이 단순히 Windows 10에서만 발생하는 것인지 어떤지는 잘 모르겠네요.
지금은 windows 8 이하 환경을 보유하고 있질 않아서...
확실한 건, Windows 10으로 오면서 윈도우 자체의 기존 폰트 중에서도 동일하게 
특수문자가 1칸으로 표시되는 폰트들이 종종 있는 듯 합니다. )

**Comment by theGivingTree** [comment]
다른 고정폭 폰트들을 보면 대부분 반각이던데 일관성을 위해서는 어쩔 수 없지 않을까요

**Comment by okgosu** [comment]
의견은 감사하나 다른 코딩 폰트도 반각이 적용이 되어 있어서 수정은 어렵겠습니다.
