### ISSUE TITLE
서로 다른 코드의 홑따옴표(그리고 겹따옴표)들이 구분이 되질 않습니다.

### ISSUE THREAD

**Issue by theGivingTree** [naver/d2codingfont#39]
U+0022 "
U+201C “
U+201D ”

U+0027 '
U+2018 ‘
U+2019 ’

U+0022 와 그 아래의 2개의 문자가 구분이 되질 않습니다.
U+0027 의 경우도 마찬가지입니다.

![comp](https://cloud.githubusercontent.com/assets/6695226/22171940/9b5ce216-dfdd-11e6-8eee-556a10dc1450.PNG)

**Comment by okgosu** [comment]
네, 의견 감사합니다.
확인해보겠습니다.

**Comment by okgosu** [comment]
https://github.com/naver/d2codingfont/releases/tag/VER1.3 에 반영되어 이슈 종료합니다. 감사합니다.
