### ISSUE TITLE
1.2 다운로드 링크 잘못됨

### ISSUE THREAD

**Issue by changwoo** [naver/d2codingfont#40]
https://github.com/naver/d2codingfont/releases 페이지에서,

VER1.2/D2Coding-1.2.zip 파일을 가리키고 있는데 VER1.21/D2Coding-1.2.zip 파일이 맞는 것 같네요.

**Comment by maxtortime** [comment]
말씀하신대로 수정했습니다. 다운로드 가능하실 겁니다.
