### ISSUE TITLE
ligature 기능 추가요청드립니다.

### ISSUE THREAD

**Issue by devsejong** [naver/d2codingfont#41]
안녕하세요. 공개해주신 D2Coding을 항상 잘 사용하고 있어서 감사하다는 말씀 먼저 드리고 싶네요.

최근에 에디터들에서 기호에 대한 가독성을 높일수 있는 Ligrature 기능이 많이 들어가고 있습니다.
https://github.com/tonsky/FiraCode

https://github.com/JAVACAFE-STUDY/D2Coding-Ligatures
직접 두 폰트를 합쳐 제작해보았지만, 고정형 글꼴이 풀리고 일관성이 떨어지는 등 많이 미숙하네요

다음버전의 D2Coding에서 정식적으로 기능 추가를 부탁드리고 싶습니다.

**Comment by okgosu** [comment]
네, 의견 감사합니다.

**Comment by okgosu** [comment]
https://github.com/naver/d2codingfont/releases/tag/VER1.3 에 반영되어 이슈 종료합니다. 감사합니다.
