### ISSUE TITLE
VS2015 글꼴 장평 및 자간 문제 (글자 크기 8pt)

### ISSUE THREAD

**Issue by hasol81** [naver/d2codingfont#43]
1.0 버전과 1.2 버전이 다음과 같이 크기 8pt 에서 다르게 보입니다.

1.2 버전의 경우 글꼴이 너무 좁고 다닥다닥 붙어 있어서 가독성이 떨어집니다.

이전에도 리포트를 했었는데, 아직 해결이 안 된 것인지 궁금합니다.

1. VS2015에 1.0 버전 폰트 적용, 글자 크기 8pt
![20170706-154752](https://user-images.githubusercontent.com/6386799/27898973-5306e5d0-6263-11e7-843a-00c1171b8662.png)

2. VS2015에 1.2 버전 폰트 적용, 글자 크기 8pt
![20170706-155135](https://user-images.githubusercontent.com/6386799/27898974-5309181e-6263-11e7-9c73-654f63459bbe.png)

**Comment by okgosu** [comment]
1.0에서 문제는 폰트 크기에 따란 한/영 비율이 맞지 않는 현상이 있어서,
1.2에서 2:1의 폭으로 맞게 수정했습니다.
폰트의 폭은 오류라기 보다는 디자인 특성이라, 
1.0버전 처럼 다시 폭을 조정할 수는 없으므로, 폰트 크기를 8이 아닌 다른 최적의 값으로 조정하시길 바랍니다.
