### ISSUE TITLE
11pt에서 글자 간격이 너무 좁네요.

### ISSUE THREAD

**Issue by Luberen** [naver/d2codingfont#45]
![fontissue](https://user-images.githubusercontent.com/26616056/28260500-4a3452c4-6b16-11e7-8e36-6296a471691e.png)

비주얼 스튜디오 2017에서 테스트해봤습니다.
10pt 이하는 너무 작고, 12pt 이상은 너무 커서 11pt가 딱 적당한 것 같은데...
문제는 자간이 너무 좁아 따닥따닥 붙어서 출력이 됩니다.
namespace만 봐도 글자들이 숨막힐 듯이 붙어 있네요.
파이참에서는 정상적으로 출력되는데 VS/이클립스에서만 자간이 좁게 나오는 것 같습니다.
보완이 필요해 보입니다.

**Comment by okgosu** [comment]
개선 가능 여부는 현재 주신 내용으로는 판단이 어렵습니다. 
게다가 특정 개발환경에서만 발생하는 이슈는 폰트 자체의 문제인지 아닌지 판단하는데도 시간이 걸립니다. 
폰트 개발사측에 확인해야하고 하니, 답변이 상당히 늦더라도 이해해주세요.

**Comment by Luberen** [comment]
천천이 수정하셔도 되는데 하나만 더 건의드리자면
알파벳 b, d의 윗꼭지가 너무 짧아서 가끔씩 n이나 o처럼 보입니다.
알파벳 h 역시 n처럼 보일 때가 있구요.
웬만하면 헷갈릴 일 없긴 한데 단어들 속에 묻혀 있다보면 종종 생기는 일이라...
가능하다면 이것도 수정되었으면 합니다.

**Comment by okgosu** [comment]
이 부분은 폰트 자체의 특성이라 양해해주시길 바랍니다.
감사합니다.
