### ISSUE TITLE
d2 1.2 jetbrains 글꼴 깨짐 현상 다시.

### ISSUE THREAD

**Issue by crucifyer** [naver/d2codingfont#46]
https://github.com/naver/d2codingfont/issues/34

![image](https://user-images.githubusercontent.com/1300668/28407338-be4ed030-6d6e-11e7-8c27-83a0430d5217.png)

댓글 달아서 이슈 다시 여는 기능이 없어서 새로 적었습니다.

**Comment by okgosu** [comment]
기존 이슈 오픈했으니, 본건은 close합니다.
