### ISSUE TITLE
2바이트특수문자들 중에 간격이 2칸이 아닌경우가 많습니다.

### ISSUE THREAD

**Issue by sechky** [naver/d2codingfont#47]
ㅂ의 한자로 나오는 특수문자등 2바이트 문자중에 2칸간격으로 그려지지않는게 많네요. 1.1버전에서는 2칸씩 차지했는데 이번패치후에 이미지 디테일은 좋아졌지만 1칸만 자지하네요.. 개선 가능한가요?

**Comment by okgosu** [comment]
코딩 서체들은 반각(1칸)으로 되어 있어 일부러 그렇게 한건데요.
어떤 글자 입력이 가장 불편하신가요? (좀 구체적으로 알려주시면...저희도 문제 파악하는데 시간을 줄일 수 있겠습니다.)

**Comment by okgosu** [comment]
특수문자의 경우 다른 코딩폰트도 1칸이므로 본 이슈는 종료하겠습니다.
