### ISSUE TITLE
얇은 폰트가 있었으면 좋겠네요.

### ISSUE THREAD

**Issue by reznoa** [naver/d2codingfont#48]
여러가지 맘에 드는점이 많긴한데,
기본 폰트가 다른 폰트의 Bold다 싶을 정도로 두껍네요.
두께가 얇은 버전이 있으면 좋겠습니다.

**Comment by okgosu** [comment]
아쉽지만, 더 가늘게 만들기는 어렵고요. 나눔고딕코딩이 있습니다. 

https://github.com/naver/nanumfont

**Comment by reznoa** [comment]
아쉽네요. 나눔고딕코딩보다 가독성이 좋다고해서 써보고 있는거라.. 다른 폰트도 알아보도록 하겠습니다.
