### ISSUE TITLE
unicode 문자를 쓰면 고정폭이 깨집니다.

### ISSUE THREAD

**Issue by reznoa** [naver/d2codingfont#49]
유니코드 문자, 예를 들어 ☐,☑,☒ 같은걸 쓰면 고정폭이 깨집니다.
해당 폰트가 없어서 그런게 아닌가 싶네요.

**Comment by okgosu** [comment]
넵, 그렇습니다.

( d2coding 1.3 베타테스터 모집 중이니 관심 있으면 메일 알려주세요^^ https://github.com/naver/d2codingfont/issues/50 )

**Comment by reznoa** [comment]
일부러 그렇게 놔둔건가보군요;
