### ISSUE TITLE
clone 하거나 zip 다운로드 누르면 폰트 파일이 안들어 있어요

### ISSUE THREAD

**Issue by khanorder** [naver/d2codingfont#51]
readme.md만 포함하고 있네요

**Comment by okgosu** [comment]
네, 수정할게요. 
그 전까지는 폰트다운로드는 release에서 받아주시길 바랍니다.
https://github.com/naver/d2codingfont/releases

**Comment by okgosu** [comment]
file들 commit에 포함시켰어요. 감사합니다.
