### ISSUE TITLE
@ 한 픽셀 아래로 내려와 있습니다. (1.3beta 피드백)

### ISSUE THREAD

**Issue by ldalove** [naver/d2codingfont#52]
의도된 것인지는 모르겠으나 균형이 안 맞아 보이는 부분이네요.
![image](https://user-images.githubusercontent.com/16849963/31679077-0266833a-b3ab-11e7-87fe-e1bf888d6fdb.png)
한 칸 올려서 다른 특수문자와 동일 선상에 놓는 것이 보기 좋지 않을까요?

**Comment by okgosu** [comment]
방금 수정 버전 메일로 드렸습니다. 확인 부탁드릴게요.

**Comment by okgosu** [comment]
https://github.com/naver/d2codingfont/releases/tag/VER1.3 에 반영되어 이슈 종료합니다. 감사합니다.
