### ISSUE TITLE
<= 문자에 대한 의견 (1.3베타)

### ISSUE THREAD

**Issue by jgh0721** [naver/d2codingfont#53]
먼저, 베타버전을 공개해주셔서 잘 사용하고 있습니다. 

<= 문자에 대해 아래와 같이 표시되는데, 

![image](https://user-images.githubusercontent.com/1096534/31981333-88da3852-b98d-11e7-9497-8c9b65a2278b.png)

기울이지 않고, 아래 이미지의 세번째와 같이 표시하는 것이 좀 더 가독성이 좋지 않을까합니다. 
![image](https://www.utf8icons.com/character_image/8804-less-than-or-equal-to-utf-8-character.png)

**Comment by okgosu** [comment]
네, 이 부분 수정 가능한지 확인해보겠습니다.

**Comment by okgosu** [comment]
이건 개인의 취향인거 같아요...내부 논의 결과 현재 디자인을 유지하는걸로 정리했습니다. 의견 감사합니다
