### ISSUE TITLE
[1.3베타] VS Code 에서 몇몇 문자가 분리됩니다. 

### ISSUE THREAD

**Issue by jgh0721** [naver/d2codingfont#54]
값, 각, 등의 문자를 입력하면 화면에 표시될 때 가ㅅ 가ㄱ 식으로 표시됩니다. 하지만 이 글자들을 복사해 다른 편집기에 넣으면 정상적으로 표시됩니다. 

갑 => 가ㅂ
값 => 가ㅅ 
각 => 가ㄱ
갖 => 가ㅉ 

등으로 표시됩니다. 가 와 조합될 때 문제가 발생하는 것 같네요. 

VSCode 는 1.17.2 입니다.

**Comment by jgh0721** [comment]
![image](https://user-images.githubusercontent.com/1096534/32532477-f34da66e-c48d-11e7-8502-9feef2772bf6.png)

**Comment by okgosu** [comment]
맑은고딕에서도 동일한 증상이 발견되는지 확인해 주실 수 있나요?

저희가 테스트한 결과 해당 현상이 재현 안되어서요.

위의 이슈는 폰트 이슈가 아니라, 개발환경 이슈 같습니다.

**Comment by jgh0721** [comment]
아, 그러고보니 Linux 이며 Kubuntu 17.10 을 사용하고 있습니다.

**Comment by okgosu** [comment]
D2Coding 이슈는 아닌 것으로 파악되었습니다. 폰트 재설치를 해보시길 바랍니다.
