### ISSUE TITLE
powerline 심볼이 설치된 것 맞나요?

### ISSUE THREAD

**Issue by rlj1202** [naver/d2codingfont#55]
일단, 폰트 미리보기에서 "버젼: Version 1.2; Build 20160909"라고 나옵니다. 단순히 버젼 정보를 업데이트 하지 않은것인지 파일을 잘못 올리신건지 궁금합니다.

![_2017_11_29_12_38_51_707](https://user-images.githubusercontent.com/10295515/33356884-4e9abf64-d502-11e7-84c4-78b0b18a39de.png)

그리고 파워라인 폰트는 E0A0번지 부터 시작하는데 폰트 뷰어로 확인한 결과 아무것도 없네요.

![_2017_11_29_12_38_22_68](https://user-images.githubusercontent.com/10295515/33356883-4e745f22-d502-11e7-97b7-f72d707e02c5.png)

파워라인 심볼이 들어있는 폰트라면 아래와 같이 심볼들이 보여야 하는데 말이죠.(DejaVu Sans Mono for Powerline)

![_2017_11_29_12_41_31_161](https://user-images.githubusercontent.com/10295515/33356932-a5552830-d502-11e7-9472-016f737d2442.png)

이 점 확인부탁드립니다!

**Comment by okgosu** [comment]
설치한 파일 링크가 어떻게 되나요?

아래는 방금 여기서 다운받은 1.3 버전 설치 화면입니다. 

![1](https://user-images.githubusercontent.com/6773678/33361043-c7413490-d519-11e7-8b2e-5491abde7d72.PNG)

**Comment by rlj1202** [comment]
releases에서 다운받았습니다. 다시 재 다운로드 해봤는데 저는 그대로입니다.

**Comment by okgosu** [comment]
네, 저도 릴리즈에서 받았습니다. 개인 pc 환경을 다시 확인 바랍니다.
