### ISSUE TITLE
gnome terminal에서 =, <, > 가 표시되지 않습니다.

### ISSUE THREAD

**Issue by byeongkyu** [naver/d2codingfont#56]
다른 에디터들에서는입력도 잘되고 잘보이는데요.
유독 gnome-terminal에서는 위 캐릭터가 보이지 않습니다.
입력해도 공백으로 입력되고, >를 입력할 경우 =>와 비슷한 모양만 보이네요.

**Comment by okgosu** [comment]
PC 의 정확한 환경이 어떻게 되나요?

- OS명
- OS버전
- gnome-ternminal 버전

**Comment by byeongkyu** [comment]
Ubuntu 16.04.3 LTS
Gnome-Terminal 3.18.3
지역설정은 en_US.UTF-8

입니다.

**Comment by boojongmin** [comment]
저도 동일 이슈가 있습니다.
ubuntu 16.04 LTS
GNOME Terminal 3.18.3

**Comment by happylarrykim** [comment]
Ubuntu 16.04.3 LTS/GNOME Terminal 3.18.3 동일한 이슈가 있습니다.

**Comment by okgosu** [comment]
gnome 이슈는 재현이 되지 않는다는데...폰트를 완전히 삭제하고 다시 설치해도 그런가요?

**Comment by byeongkyu** [comment]
네. 폰트 삭제하고 다시 설치해봐도 마찬가지입니다.

**Comment by okgosu** [comment]
원인 확인했고, ligature 때문인 걸로 파악되었습니다.
1.31 에서는 ligature 있는 버전과 없는 버전을 배포할 예정이오니, ligature없는 버전을 설치해주시면 될 거 같습니다.

**Comment by okgosu** [comment]
1.31 버전을 릴리즈 하여 본 이슈는 해결되어 종료합니다.
( ligature 없는 버전으로 설치하시면 됩니다.)
