### ISSUE TITLE
'@' 기호가 1.3에서 변경된 것 같은데 별다른 이유가 있나요?

### ISSUE THREAD

**Issue by HealGaren** [naver/d2codingfont#57]
![image](https://user-images.githubusercontent.com/13010755/33473043-2af253b2-d6b8-11e7-9da6-d0cc26ab03f9.png)
(15pt, Windows, IntelliJ, 문자열 서식)
상단이 1.3, 하단이 1.2인데 '@' 기호가 이전과 비교했을 때 하단이 붙어서..
개인적으로 보기 불편해진 것 같아요 ㅜㅜ
업데이트 내역에 해당 이야기가 없어서 혹시 변경된 이유가 있는지 여쭤보고 싶습니다.

**Comment by okgosu** [comment]
15pt만 그런가요? 
OS, 개발도구의 정확한 버전이 어떻게 되나요?

**Comment by HealGaren** [comment]
개발도구는 IntelliJ 2017.3버전, OS는 Windows 7입니다.
![image](https://user-images.githubusercontent.com/13010755/33542483-98b46d76-d916-11e7-8a90-12609906dcd2.png)
D2Coding 1.3의 제 환경에서의 왼쪽부터 13pt~20pt의 일반적인 골뱅이와 문자열 골뱅이의 모습입니다.
15pt 문자열 상태에서 보기 불편한 부분이 있는 것 같습니다.

**Comment by okgosu** [comment]
수정 진행 중입니다. 1.31로 배포할 예정입니다.

**Comment by HealGaren** [comment]
감사합니다 :)

**Comment by okgosu** [comment]
1.31 버전에 수정하여 배포하였습니다.
