### ISSUE TITLE
특정 프로그램에서 폰트 깨짐 현상

### ISSUE THREAD

**Issue by littmus** [naver/d2codingfont#58]
1.2 버전은 putty에서 정상적으로 사용중이였는데, 삭제 후 1.3 버전을 설치하니 다음과 같이 깨져서 한글이 정상적으로 표시되지 않습니다
윈도우7 입니다
![image](https://user-images.githubusercontent.com/1590516/33538069-9360be92-d902-11e7-9336-f50b671bcf59.png)

**Comment by kaisyu** [comment]
실행 중인 PuTTY 프로그램을 모두 다 닫고 다시 실행해보세요.

**Comment by littmus** [comment]
아 해결되었습니다 감사합니다!
