### ISSUE TITLE
ligature 를 사용하지 않고 싶어서 1.2를 사용중인데요, 1.3에서 ligature없는 버전은 없나요?

### ISSUE THREAD

**Issue by chance-huh** [naver/d2codingfont#59]
Visual Studio 2015 C#에서 ligature 를 사용하지 않고 싶어서 D2Coding 1.2로 다시 복귀했습니다.
혹시, 1.3에 ligature없는 버전은 계획이 없나요?

**Comment by sundae21c** [comment]
Powerline까지 OK
적응, 취향, 유행의 문제인지는 모르겠습니다만,
Ligature는 Underline 개수 구분 불가능해지는 거나, 이래저래 봤을 때
처음 목표했던 바와는 좀 멀어져버린 게 아닌가요?

**Comment by okgosu** [comment]
ligature 없는 버전이랑 있는 버전 2가지로 준비해서 배포할 예정입니다.
의견 감사합니다.

**Comment by yuaming** [comment]
Ligarue 없는 버전이 얼른 나왔으면 좋겠습니다:)

**Comment by zelon** [comment]
저도 ligature없는 버전이 얼른 나왔으면 좋겠습니다. 좋은 글꼴 감사합니다!

**Comment by okgosu** [comment]
1.31 버전 릴리즈함으로써 본 이슈 종료합니다.
