### ISSUE TITLE
ligature가 모든 IDE에 적용되는 건 아니네요.

### ISSUE THREAD

**Issue by Luberen** [naver/d2codingfont#60]
비주얼 스튜디오랑 스파이더 IDE는 ligature가 적용되는데,
안드로이드 스튜디오와 이클립스에서는 적용이 안 됩니다.
그리고 ligature는 포함 버전/미포함 버전으로 옵셔널하게 배포하는 것이 낫지 않을까 싶습니다.
너무 적응이 안 되네요.

**Comment by okgosu** [comment]
ligature 없는 버전이랑 있는 버전 2가지로 준비해서 배포할 예정입니다.
의견 감사합니다.
