### ISSUE TITLE
ligature 적용에 오류를 발견했습니다.

### ISSUE THREAD

**Issue by hi4324** [naver/d2codingfont#61]
사용하는 툴은 VS2015입니다.
 A != B && C != D && ... 에서 
첫번째 != 는 '≠' 으로 정상적으로 표현이 되는데
두번째 이후의 !=는 '!='으로 표현됩니다.

**Comment by okgosu** [comment]
확인 중입니다.

**Comment by okgosu** [comment]
재현이 되지 않아 처리가 어려우니, 재현 방법을 다시 알려주시길 바랍니다.
