### ISSUE TITLE
윈도우10에서 설치가 안되네요

### ISSUE THREAD

**Issue by soulysy** [naver/d2codingfont#62]
윈도우10에서 설치가 안되요 ㅜㅜ
설치하는 방법이 따로 있는건가요??

**Comment by rtboss** [comment]
다운로드 후 압출풀고
C:\Windows\Fonts
폴더에 복사하시면 됩니다.

**Comment by soulysy** [comment]
말씀하신 방법도 해보고 파일에서 마우스 오른쪽 클릭후 설치도 해봤는데 안되네요
올파른 폰트파일이 아닙니다 라는 메세지가 나옵니다.

**Comment by rtboss** [comment]
저는 위 방법으로 진행 시 문제가 없었는데요.!
다른 폰트도 동일한 문제가 발생하나요.??

**Comment by soulysy** [comment]
나눔고딕 코딩도 동일증상 발생했어여

**Comment by okgosu** [comment]
이슈가 재현이 되지 않아, 개인 pc 환경 이슈로 판단됩니다.
