### ISSUE TITLE
VIM에서 커서컬럼 표시줄 사용시 이슈하나 있어요.

### ISSUE THREAD

**Issue by mosaicstory** [naver/d2codingfont#63]
VIM의 .vimrc 에
**set cusorcolumn**
을 적용하면 현재 커서 위치 컬럼들에 대해 세로줄이 하나 생깁니다.(컬럼스킴에 따라 색깔이나 밑줄로만 보여질수도)

 커서컬럼줄이 나오는 상태에서 좀더 현상이 잘보이긴하는데,  컬럼줄안나와도
텍스트파일내에서 심볼문자, 예를들어 '◼︎','[' 같은글자, 하나 넣고 문장을 쓰려고하면

> ◼︎ [섹션] 주제...
>     내용..블라블라...

와 같이 쓰고나서 '[' 근처를 커서이동하다보면  '['글자가 좌/우로 이동되는 현상이 나옵니다.

테스트환경
Windows 7에서 SecureCRT 6.2.3 사용하여 Red hat Linux 터미널접속, vim 7.2로 텍스트파일작성.

Bitstream Vera Sans Mono 사용했을땐 안생기는데, D2coding에서만 생기네요.
아마도 해결책이 있지 않을까 싶어 글 남겨봅니다.

**Comment by mosaicstory** [comment]
계속 사용하다보니, 터미널상에서 vim 사용할때만 나오네요. (다른 에디터, 심지어 gvim에서도 안나타나네요)

**Comment by okgosu** [comment]
에러 재현이 안되어서 ligature  이슈로 보이는데요...
 '1.3.1 ligature 미적용 버전' 을 써보시길 바랍니다...
