### ISSUE TITLE
ligature를 Webstorm에서 지원 가능한가요?

### ISSUE THREAD

**Issue by Shin-JaeHeon** [naver/d2codingfont#65]
Webstorm에선 ligature기능을 키는 버튼이 활성화 되지 않는데, 지원 해 주실 수 있으시나요?

**Comment by okgosu** [comment]
'Font' 항목에 D2Coding ligature을 지정하고, 'Enable font ligatures'를 설정하시면 됩니다. 
 
![image](https://user-images.githubusercontent.com/6773678/35110676-bcaf34b2-fcbc-11e7-9564-62dd9e3451a2.png)

**Comment by Shin-JaeHeon** [comment]
![image](https://user-images.githubusercontent.com/21238436/35133648-b07c9826-fd14-11e7-998f-732a21d31610.png)
왜 이러는지 알 수 있을까요? 사용환경은 2017.2.3, Windows 10 RS3입니다.
