### ISSUE TITLE
1.3에서 1.31 버전업이 소숫점 0.01 추가의 의도인가요?

### ISSUE THREAD

**Issue by changwoo** [naver/d2codingfont#66]
안녕하세요. 데비안에서 fonts-naver-d2coding 패키지를 만드는 류창우입니다.

1.31 버전 보고 질문 드립니다. 1.3 다음 버전이 1.31인데 0.01을 추가한 1.31인가요? (1.4보다 작은 버전?) 이게 틀렸다는 건 아니고 만약 그렇다면 일반적이지 않기 때문에 패키징 관련해서 알아놓아야 할 것 같아서요. 대부분 오픈소스의 버전에서 점은 소숫점을 의미하는 게 아니거든요. 1.9 다음에 1.10, 1.11 이렇게 버전이 진행하고 데비안은 물론이고 보통 패키징 시스템의 버전 비교하는 코드도 그렇게 비교하게 되어 있습니다.

**Comment by jhyeon** [comment]
"이게 틀렸다는 건 아니고" 다음에 나오는 모든 부연설명이 이게 틀렸다는 뜻으로 읽히네요.  그 구절이 틀렸다는 건 아닙니다.  :)
다음 버전은 1.40이나 2.0으로 하시겠지요.

**Comment by okgosu** [comment]
네, 1.3에서 크게 기능이 안들어갔기에 1.31로 했고요.
만약 다음 릴리즈를 하게 된다면 1.4가 되겠지요.

**Comment by benelog** [comment]
@okgosu 
그러면 1.3.1 이 되어야하지 않나요? 1.31 은 1.4보다 큰 숫자로 인지될수 있습니다.

**Comment by okgosu** [comment]
D2코딩의 내부 버전 정보는 1.3.1 로 지정되어 있습니다... file명과 릴리즈 노트 수정할게요...제보 감사합니다.

**Comment by okgosu** [comment]
변경했습니다.
