### ISSUE TITLE
AndroidStudio 에서 bold 상태의 'y'가 작습니다.

### ISSUE THREAD

**Issue by x1306e6d** [naver/d2codingfont#67]
아래 사진에서 보시다시피 bold 상태의 'y'가 다른 글자들에 비해 작아 보입니다.

![20180224_161240](https://user-images.githubusercontent.com/15008311/36626854-9d3c38f4-197d-11e8-8a05-4738266f0f2e.png)

**Comment by okgosu** [comment]
폰트개발사측에 이슈 전달했습니다. 차주 중으로 회신이 오면 업데이트 드릴게요.

**Comment by benelog** [comment]
1.3.2 버전에 개선 반영되었습니다.

https://github.com/naver/d2codingfont/releases/tag/VER1.3.2 에서 다운로드 하실 수 있습니다.
