### ISSUE TITLE
특정 글자의 크기가 다른 글자보다 작아지는 문제

### ISSUE THREAD

**Issue by Luberen** [naver/d2codingfont#70]
![d2font](https://user-images.githubusercontent.com/26616056/37954572-334cdef4-31e1-11e8-8b26-65871fe11e92.png)

18pt에서 i가 다른 글자보다 길이가 짧게 표시되어 상대적으로 들쭉날쭉해 보입니다.
사진은 Windows 10, 안드로이드 스튜디오 3.1에서 테스트한 결과입니다.
이 현상은 Visual Studio Code에서도 발생합니다.

**Comment by okgosu** [comment]
폰트개발사측에 이슈 전달했습니다. 차주 중으로 회신이 오면 업데이트 드릴게요.

**Comment by Luberen** [comment]
답변 감사합니다.

**Comment by benelog** [comment]
1.3.2 버전에 개선 반영되었습니다.

https://github.com/naver/d2codingfont/releases/tag/VER1.3.2 에서 다운로드 하실 수 있습니다.

**Comment by Luberen** [comment]
수정 감사드립니다. 그런데 'ㅔ'에서 바깥쪽 횡의 길이가 줄어드는 건 개선된 게 맞나요?
![11](https://user-images.githubusercontent.com/26616056/40818648-2831e6be-6593-11e8-94ab-0b46bd628c2e.png)
지금 확인해 보니까 이 부분은 그대로여서요.
