### ISSUE TITLE
윈도우 인텔리제이에서 폰트 리스트에 나타나지 않습니다.

### ISSUE THREAD

**Issue by LeeKyoungIl** [naver/d2codingfont#78]
안녕하세요. 제 노트북에 d2코딩 폰트를 전부 설치 했습니다.
windows/font 폴더에 D2Coding, D2Coding ligature 있는것 확인 했습니다. 

재부팅을 해도 intellij 의 font list에 나타나지 않습니다. 
도움좀 받을 수 있을까요?

D2Coding Ver 1.3.2를 설치 했으며 OS 는 Windows 10 pro for Workstations 입니다. (빌드 1809)

**Comment by LeeKyoungIl** [comment]
인텔리제이는 아래와 같습니다.

IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by benelog** [comment]
사내 개발자들 사이에 비슷한 현상을 겪은 사람이 있는지 수소문해보고 있는 중입니다.

**Comment by silencerwon** [comment]
* 비슷한 문제를 겪었는데 해결되었네요. 동일한 증상인듯 싶어서 공유드립니다. 
  * D2 폰트 파일을 우클릭하시고 노출되는 컨텍스트 메뉴중 "모든 사용자로 설치" 로 재설치하신 후, 인텔리제이를 재시작하신 후 확인해보시면 될듯합니다. 
  * 관련링크: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360001112320-Idea-does-not-recognize-the-new-fonts-added-to-windows10-LTSC-2019-version

**Comment by LeeKyoungIl** [comment]
@silencerwon 옷 감사합니다! 그렇게 한번 해보겠습니다.

**Comment by jaehoonx2** [comment]
@silencerwon 안드로이드 스튜디오에서도 동일한 현상이 있었는데 해결했네요! 감사합니다.

**Comment by ikpil** [comment]
@silencerwon 
저도 같은 문제 해결 되었는데, 알려 주신 방법으로 하니까 잘 되었습니다.
공유해 주셔서 감사합니다.

**Comment by sappho192** [comment]
@LeeKyoungIl 안녕하세요, 문제가 해결되셨다면 이슈를 닫아주시는게 좋을 것 같아요 😊

**Comment by LeeKyoungIl** [comment]
이슈 해결됨

**Comment by ipari** [comment]
@silencerwon 감사합니다 덕분에 저도 문제 해결했습니다.

**Comment by jungwone** [comment]
@silencerwon  감사합니다 저도 해결이요 !!

**Comment by M1nseokSong** [comment]
해결!
